### ISSUE TITLE
component lifecycle hook triggered twice

### ISSUE THREAD

**Issue by ghost** [fyodorio/ng-hotrod#18]
- [x] I have searched the [issues](https://github.com/loenko/ng-hotrod/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

component lifecycle hook triggered once 

## Current Behavior

component lifecycle hook triggered **twice**
 
## Steps to Reproduce (for bugs)

1. write anycode in `component` lifecycle hook, for example: 
```js

	$onInit(){
		console.log('Hello World')
	}
```
2. run "yarn dev" and look at browser's console in devtool
3. then you can see "Hello World" twice

![image](https://user-images.githubusercontent.com/77133362/141682651-04cb9130-06be-485b-af65-f77f66b67814.png)

## Context
    
reproduce example: https://github.com/iceytea/ng-hotrod/tree/iceytea-bug-reproduce-for-triggered-twice

exact position: https://github.com/iceytea/ng-hotrod/blob/iceytea-bug-reproduce-for-triggered-twice/app/app.component.js#L8

**Comment by iceytea** [comment]
https://github.com/fyodorio/ng-hotrod/pull/19

**Comment by fyodorio** [comment]
Closed by #19 (thanks @iceytea 💪)
